services:

  alpha-arena-okx:
    image: xxfcloud.tencentcloudcr.com/comm/tools/alpha-arena-okx:v2.4.2
    container_name: alpha-arena-okx
    restart: always
    ports:
      - "8501:8501"
    volumes:
      - /etc/localtime:/etc/localtime
      - ./alpha-arena-okx/data:/data
      - ./alpha-arena-okx/.env:/app/.env
      - ./alpha-arena-okx/trading_data.json:/app/trading_data.json
      - ./alpha-arena-okx/trades_history.json:/app/trades_history.json
      - ./alpha-arena-okx/equity_history.json:/app/equity_history.json
    environment:
      # 时区上海
      TZ : Asia/Shanghai
      #- DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      #- OKX_API_KEY=${OKX_API_KEY}
      #- OKX_SECRET=${OKX_SECRET}
      #- OKX_PASSWORD=${OKX_PASSWORD}
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -f http://localhost:8501/_stcore/health && pgrep -f 'python.*run.py'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"